### ISSUE TITLE
Grammar is always ambiguous, not only in list context

### ISSUE THREAD

**Issue by lrhn** [leafpetersen/dep-generic-methods#4]
The syntax `e1<e2>(e3)` is already ambiguous, no commas necessary since any object can implement the `<` and `>` operators. Highly questionable example:

``` dart
class Cast {
   final Type type;
   const C([this.type]);
   C operator <(Type t) { return new Cast(T) }
   operator >(value) { ... magic stuff involving type and value ... }
}
const cast = const Cast();
```

which can then be used as `cast<int>(42)`.

A more relevant mini-language, using noSuchMethod for great evil, could be:

``` dart
    html<div.title="something"> ("body text: " + input) <-div>html
```

(That should be doable)
That kind of usage might be unlikely, with `foo(2 < x, y > (z+w))` being more likely to happen in practice, but being ambiguous is still sucky.

Some other possible alternative syntaxes for calling `T foo<T>(T x)` than the alternatives in the proposal (not that they are any better):

``` dart
    <int>foo(42)
    foo.<int>(42)  // or
    foo@<int>(42)  // or some other unused characters like ':' or '::'
    foo(<int>, 42)  // nah!
```

I agree that if we can get the proposed syntax through (breaking changes are hard to sell), it is clearly the best option because it matches the corresponding use on constructors.

**Comment by munificent** [comment]
> The syntax e1<e2>(e3) is already ambiguous, no commas necessary since any object can implement the < and > operators. 

I thought avoided that already by disallowing chained relational operators:

```
relationalExpression:
  bitwiseOrExpression (typeTest | typeCast | relationalOperator bitwiseOrExpression)?
```

**Comment by lrhn** [comment]
Ack, you are right. I forgot that restriction (and that ruins my nice html mini-language too! Bugger!)

**Comment by leafpetersen** [comment]
This is definitely a good thing to keep pushing on, both to be sure that I haven't missed an ambiguity, and also to see if the collective wisdom can come to a better solution (particularly in the case that the backwards incompatibility is deemed unacceptable).  I do feel that it would be really regrettable to saddle ourselves with an ugly syntax that we would never have chosen if we were designing a language from scratch.
